# The default config toml.
root_url = "/"
redis_url = "redis://127.0.0.1/"
postgres_url = "postgres://postgres:SOME_STRONG_PASSWORD@127.0.0.1/wechat_push"

[wechat]
app_id = "Wechat MP App ID"
app_secret= "Wechat MP App secret"
token = "token"
default_template_id = "wTRJ7BhhYqm54ppNo-87zDbtLJHOd8b16O3HAkv-yBE"
detail_url = "https://web.example.com/detail/"
