refresh_rate: 30 seconds

# i.e. handler
appenders:
  stdout:
    kind: console
    # i.e. formatter
    encoder:
      kind: pattern
      pattern: "{date(%H:%M:%S)} [{highlight({level})}] (({target}:{line})) - {message}{n}"
  server_rs:
    kind: rolling_file
    path: log/server_rs.log
    policy:
      kind: compound
      trigger:
        kind: size
        limit: 10mb
      roller:
        kind: fixed_window
        pattern: log/server_rs.{}.log
        count: 5
        base: 1
    encoder:
      kind: pattern
      pattern: "{date(%Y-%m-%d %H:%M:%S)} [{level}] (({target}:{line})) - {message}{n}"

root:
  level: info
  appenders:
    - stdout

loggers:
  server_rs:
    level: debug
    appenders:
      - server_rs
      - stdout
    additive: false
